services:
  openguessreducation:
    image: openguessreducation
    container_name: openguessreducation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 2798:3000