version: '3.4'

services:
  openguessreducation:
    image: openguessreducation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4180:4173